### ISSUE TITLE
Statistical test for obtained PLV scores matrix

### ISSUE THREAD

**Issue by ihgumilar** [ppsp-team/HyPyP#103]
Dear  @deep-introspection @YannBeauxis ,

I would like to ask some questions. 

I have calculated the PLV scores and obtained the matrix for that , eg. 16  channels x 16 channels. Is there a function to test statistically which connections out of 256 possible connections (16 x 16 channels) that are statistically significant ? I have a difficulty to find them.

Also, I have tried to run this https://hypyp.readthedocs.io/en/latest/API/statistics/#hypyp.stats.metaconn_matrix_2brains, but I don't quite understand the result of that function. What does the output give actually ? what is the purpose of that function. I tried to read it but could not really understand it.

I understand that the input for statistical function is PSD, yet I have a matrix of PLV scores, which cannot be an input for the statistical functions of hypyp. Can you give me some help  please ?

Thanks
Ihshan

**Comment by deep-introspection** [comment]
Dear @ihgumilar, you should use the ```stats.statscondCluster``` function as demonstrated in the [getting_started.ipynb](https://github.com/ppsp-team/HyPyP/blob/master/tutorial/getting_started.ipynb)
