### ISSUE TITLE
Error message displayed in Tutorial's Jupyter Notebook

### ISSUE THREAD

**Issue by BrainonSilicon** [ppsp-team/HyPyP#104]
Hi team! 

I noticed that the [getting_started.ipynb](https://github.com/ppsp-team/HyPyP/blob/master/tutorial/getting_started.ipynb) file contained output from when someone has run the first cell. 

Wondering if that was left in on purpose, or if it's worth taking out?

**Comment by deep-introspection** [comment]
Hi! Thanks for your kind message and raising this issue. We now have cleaned the tutorial. Cheers!
