### ISSUE TITLE
Viz function error

### ISSUE THREAD

**Issue by frederatic** [ppsp-team/HyPyP#105]
I get the following error for viz_2D_headmodel_inter() in the Viz module.

Line 742:     vertices, faces = get_3d_heads()

That function does not exist.
I only see get_3d_heads_inter() and get_3d_heads_intra() functions, so should the line perhaps be changed to one of those?

**Comment by ghazalehran** [comment]
Dear @frederatic, thanks for the feedback. I ran and check the code and I guess you are right. You can manually change the get_3d_heads() to get_3d_heads_inter(). I did this and get the result. Let me know if this works.

**Comment by frederatic** [comment]
Yes, that works. Issue will be closed.
