### ISSUE TITLE
Problem visualizing links using viz_3D_inter

### ISSUE THREAD

**Issue by CarmelGashri** [ppsp-team/HyPyP#129]
![image](https://user-images.githubusercontent.com/92847693/173526241-dad4f8f8-a0c7-42f0-94f5-5e0ec748e782.png)
Hey

I tried creating a 3D and 2D visualization using EEG data which I pre-processed using EEGLAB, however, I get the following image (attached).
Not sure what is wrong (it seems as if the heads are on top of each other).
How can I fix it?

Thank you 
Carmel

**Comment by deep-introspection** [comment]
@CarmelGashri Is the problem solved?

**Comment by CarmelGashri** [comment]
Yes

Thank you very much for your kind help
