### ISSUE TITLE
Hypyp compatibility issue with python

### ISSUE THREAD

**Issue by ihgumilar** [ppsp-team/HyPyP#136]
I am wondering whether the latest version of hypyp is compatible with the latest version of python (version 3.9) ?
That would be great if you could clarify this in the installation section, mentioning which python version that is compatible with hypyp. Previously it is mentioned that it still has an issue with python 3.9. In other words, it is only compatible with **python 3.8** only.

It will save the time of newbie who is trying to use this package instead of debugging such incompatibility issue.

Thanks
IG

**Comment by deep-introspection** [comment]
It works from 3.7 to 3.9 technically.
