### ISSUE TITLE
can't find mne.channels.find_ch_connectivity in the MNE v0.21.2

### ISSUE THREAD

**Issue by YouyanLee** [ppsp-team/HyPyP#41]
I am using MNE v0.21.2, but pop up the error "can't find mne.channels.find_ch_connectivity " when loading modules.
I noticed that this method is no long in MNE version>0.20. Maybe HyPyp should be updated to fixed this problem, too.

**Comment by deep-introspection** [comment]
Thanks @YouyanLee ! We just pushed a correction on the Main branch. Can you check this is working on your side?

**Comment by YouyanLee** [comment]
It works fine now. Thank you!
