### ISSUE TITLE
Negative ccorr values when running tutorial

### ISSUE THREAD

**Issue by KathrineSN** [ppsp-team/HyPyP#46]
Hi,
I am running your function analyses.compute_sync(complex_signal, mode='ccorr'). From there I slice the inter-brain part of the matrix [:, 0:n_ch, n_ch:2*n_ch] as it is done in your tutorial. However, when I calculate the circular correlation values this way it seems that I get negative values... which confuses me as circular correlation should be between 0 and +1. Is there an explanation for getting negative values, and how do I interpret them? 

Thank you,

Kathrine

**Comment by deep-introspection** [comment]
Dear @KathrineSN, there is no problem. CCOR can take values from -1 to +1. If you want a absolute measure of the circular correlation, you can apply `np.abs` to the result.
