### ISSUE TITLE
find_ch_connectivity is no longer in use in mne

### ISSUE THREAD

**Issue by ihgumilar** [ppsp-team/HyPyP#56]
When we try to import modules in file getting_started.py, there is an error

    from mne.channels import find_ch_connectivity
ImportError: cannot import name 'find_ch_connectivity' from 'mne.channels' (/hpc/igum002/environments/mne_py39/lib/python3.9/site-packages/mne/channels/__init__.py)

Apparently, if we read the documentation of mne that[ `find_ch_connectivity`](https://mne.tools/stable/whats_new.html) has been replaced with `find_ch_adjacency`

That would be great if you could update in your function there.

Thanks
Ihshan

**Comment by deep-introspection** [comment]
It's corrected now!
