### ISSUE TITLE
Unable to install the latest hypyp release

### ISSUE THREAD

**Issue by ihgumilar** [ppsp-team/HyPyP#57]
Hi,

I am trying to install the latest release of hypyp. When I run `pip install hypyp`
I have got an old version being installed
![image](https://user-images.githubusercontent.com/49016400/125383448-839f3180-e3eb-11eb-999a-95e297c7c849.png)

However, when I run `pip install hypyp==0.3.0b2`  or `pip install hypyp --upgrade`
It gives me the following error. Could you guys give me some help ? Fyi, I installed it in headless server linux with python 3.9.

![image](https://user-images.githubusercontent.com/49016400/125384045-72a2f000-e3ec-11eb-8bad-024c716c16f4.png)

As additional information, I tried to create a new environment with python3.6 and install the latest package in pip, yet I have got the following error

![image](https://user-images.githubusercontent.com/49016400/125391174-1c3bae80-e3f8-11eb-8032-dd71793c43fa.png)

Thanks

**Comment by YannBeauxis** [comment]
Hi,
There's dependencies issues with python 3.9.
As a short term workaround, it should work with python 3.7 or 3.8.
