### ISSUE TITLE
What input does analyses.compute_freq_bands expect?

### ISSUE THREAD

**Issue by MLTOL** [ppsp-team/HyPyP#75]
Hi,

Congratulations on your HyPyp pipeline. I am trying to implement your HyPyP pipeline for our own data. Unfortunately, I have an issue with the analysis pipeline. 

We use EEG signals obtained by the MUSE S. Data is stored in XDF files, which I converted to mne objects. Since we use the MUSE S the montage is standard 1020, but only the TP9, TP10, AF7 and AF8 are included. I included our events in our data and created an epoch object based on these events. I was able to run the preprocess pipeline correctly. 

Please, could you tell me what data format is required for the methods functions in the analyses pipeline? We were able to apply the autoreject. Then, following your manuscript, I thought I should use your merge and split function to do some additional data preparation. However, when I try to run the code I get a data shape error:

![image](https://user-images.githubusercontent.com/30501164/145023550-4c2e5c7c-0d5d-4c96-8fd4-35424efc44f5.png)

![image](https://user-images.githubusercontent.com/30501164/145023581-237aad62-f6a6-44ce-9194-7962eb2981b4.png)

Alternatively, I tried to input the epochs outputted by the autoreject directly into the compute_freq_bands function. But then I got the following error:

![image](https://user-images.githubusercontent.com/30501164/145023651-b1d598c2-466a-44aa-bdba-901472185b49.png)
![image](https://user-images.githubusercontent.com/30501164/145023676-64f323a9-26f4-4eb2-aec0-c44c8accdc08.png)

Apparently, the function does not expect the mne object, but an array. I know the compute_freq_bands function expects a shape of (2, n_epochs, n_channels, n_times). What data from your pipeline does this function expect? How do I get from the output of the autoreject function to the expected data format?

I hope you can help. Thank you for your time.

**Comment by katied-neuro** [comment]
Hello, 

I think the issue is that you need to feed in an np array to compute_freq_bands that contains your two sets of epochs, similar to the data_inter framework shown in the tutorial in box 21 onwards (under connectivity). 

https://github.com/ppsp-team/HyPyP/blob/master/tutorial/getting_started.ipynb 

Please let us know if this works :)

**Comment by deep-introspection** [comment]
We will close that issue for now. Let us know if the bug is still there.
